### ISSUE TITLE
Field of view locks when certain elemental skills are held for a specific duration

### ISSUE THREAD

**Issue by z3lx** [z3lx/genshin-fov-unlock#10]
The field of view gets temporarily locked when certain elemental skills are held for a specific duration on commit [`ccc5571`](https://github.com/z3lx/genshin-fov-unlock/commit/ccc55716392d83967bfed10abcf278e29a4f90ee) of the plugin and version 5.1 of the game. Unsure if this is limited to only Keqing's E, or to all interactions that can be held and that modifies the camera's field of view. Hard to replicate.

https://github.com/user-attachments/assets/8df4e390-2669-4d72-87f6-cd345cabc15a

**Comment by Mizerka** [comment]
had similar issues with xinq ult and e, reusing the skill would often reset it back

**Comment by z3lx** [comment]
Did you experience that with the newest version of the plugin (built it yourself), or the latest release (downloaded)? I ran current abyss with Xingqiu but didn't observe any anomalies.

**Comment by z3lx** [comment]
Here's the latest version of the plugin built if you want to try it out. Let me know if it makes a difference!
[plugin.zip](https://github.com/user-attachments/files/17759850/plugin.zip)

**Comment by Mizerka** [comment]
cant replicate it reliably, but it does most often break on actions that mess with pov, just did a few abyss floors, happened with fishl e also, reset on next chacters skill, on release version, I'll try this one see how it goes

**Comment by z3lx** [comment]
I can affirm that it also happens with Fischl's E skill. I'll write some code to observe the behavior of the plugin and of the game when I have the time next week to hopefully understand why it's doing that, and find a solution.

**Comment by z3lx** [comment]
@Mizerka I've tweaked the FOV filtering algorithm a bit -- see commit [4fc6874](https://github.com/z3lx/genshin-fov-unlock/commit/4fc6874ff4da47f707da57061ec90a90b40481e5) on the [bugfix/10-fix-fov-lock](https://github.com/z3lx/genshin-fov-unlock/tree/bugfix/10-fix-fov-lock) branch. From my preliminary testing, this bug doesn't happen anymore, and there aren't really any considerable downsides to the modification. However, I'd be thankful if I could get some feedback!
[plugin.zip](https://github.com/user-attachments/files/17839881/plugin.zip)

**Comment by z3lx** [comment]
Give me a sec, just found out that I broke the FOV toggle interpolation (enable/disable with down arrow) lol

**Comment by z3lx** [comment]
Fixed with commit [507e971](https://github.com/z3lx/genshin-fov-unlock/commit/507e97171918322863516a8c51e00906ec1b40ab). Hopefully this is the last time I'll have to bother you for this, apologies haha
[plugin.zip](https://github.com/user-attachments/files/17849676/plugin.zip)

**Comment by Mizerka** [comment]
no worries, the fov plugin worked so far, did have to up arrow to hook. I'll stick new version in :)

not seen issues so far, still locked to 120fps, if we think its sorted I'll revert back to my native 180. I'll be back if I see issues
