### ISSUE TITLE
doesnt load when inside fpsunlocker folder

### ISSUE THREAD

**Issue by Mizerka** [z3lx/genshin-fov-unlock#3]
Probably obvious but took a while for me to realise, when trying to inject dll on latest v3.3 it doesnt seem to do anything when the file is inside same dir as unlocker, moved it out ot another folder which stopped truncating the path down when adding dll and it loaded as expected, probably a bug with unlocker tbh.

**Comment by z3lx** [comment]
I can replicate your issue with both the plugin (genshin_fov_unlock.dll) and 3dmigoto (d3d11.dll) -- this does seem to be a problem with the unlocker's injector itself. I'll mark this issue as closed now.
